### ISSUE TITLE
Bookmarklet

### ISSUE THREAD

**Issue by YourMajestyTheEye** [ZXMushroom63/ScratchEditor#1]
What is the code for the bookmarklet?

**Comment by ZXMushroom63** [comment]
this is the code for the bookmarklet. It is inside bookmarklet.js and just runs the code in Source.js
```
javascript: fetch(
  window.atob(
    "Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL1pYTXVzaHJvb202My9TY3JhdGNoRWRpdG9yL21haW4vU291cmNlLmpz"
  )
).then((x) => {
  x.blob().then((y) => {
    y.text().then((z) => {
      var script = document.createElement("script");
      script.innerHTML = z;
      document.body.appendChild(script);
    });
  });
});
/*/Bookmarklet/*/
```

**Comment by ZXMushroom63** [comment]
Just realized how obscure it is to figure out how to use this. Put the code directly into the readme, should be easy to find!

**Comment by YourMajestyTheEye** [comment]
Wow! Great Job! I understand most of it, but it would be nice if you explained how each block works in readme. Great work!

**Comment by ZXMushroom63** [comment]
I explain it in the help tab of the menu. It is veiwable by clicking om 'SK2 Blocks' to uncollapse the documentation

**Comment by ZXMushroom63** [comment]
i will probably make a wiki

**Comment by YourMajestyTheEye** [comment]
Thats a good idea :)
